spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smbms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19970125
  redis:
  #数据库索引
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
        max-wait: -1ms
        timeout: 3000ms
    #连接超时时间
  jackson:
    date-format: yyyy-MM-dd

mybatis:
   mapper-locations: classpath:mapper/**.xml
   type-aliases-package: cn.kgc.pojo
server:
  port: 8001